from tkinter import *
import mysql.connector

conexion=mysql.connector.connect(user='root',password='',host='127.0.0.1',database='encuesta')
cursor=conexion.cursor()

def encuesta():
    root.iconify()
    root1.deiconify()

def resultados():
    root.iconify()
    root2.deiconify()

def retornar():
    root1.withdraw()
    root2.withdraw()
    root.deiconify()

#Ventana Principal
root=Tk()
root.title("Musical taste")
root.config(bg="black")
root.geometry("850x478+100+100")
imagenT=PhotoImage(file="Person-me.png")
lblImagen0=Label(root, bd=0, image=imagenT)
lblImagen0.pack()
imagenA=PhotoImage(file="music-note-clip-art-music-note-clipart-4.png")
lblImagen1=Label(root, bd=0, image=imagenA).place(x=85, y=189)
imagenB=PhotoImage(file="music-note-clip-art-music-note-clipart-2.png")
lblImagen2=Label(root, bd=0, image=imagenB).place(x=680, y=189)
lblTexto=Label(root, text="MUSICAL TASTE SURVEY", font=("Impact", 40), fg="black",bg="#C9C9C9").place(x=175, y=80)
botonEncuesta=Button(root, text="Do survey", font=("Impact", 20), width=10, height=1, anchor="center", relief="groove", borderwidth=5, bg="#C9C9C9", activebackground="grey", activeforeground="white", cursor="hand2", command=encuesta).place(x=270, y=325)
botonResultados=Button(root, text="Results", font=("Impact", 20), width=10, height=1, anchor="center", relief="groove", borderwidth=5, bg="#C9C9C9", activebackground="grey", activeforeground="white", cursor="hand2", command=resultados).place(x=430, y=325)

#Ventana survey
root1=Tk()
root1.withdraw()
root1.title("Survey")
root1.config(bg="black")
root1.geometry("400x418+100+100")
#Scrollbar
scrollbar=Scrollbar(root1)
c=Canvas(root1, bd=0, yscrollcommand=scrollbar.set)
scrollbar.config(command=c.yview)
scrollbar.pack(side=RIGHT, fill=Y)
frame=Frame(c)
c.pack(side=LEFT, fill=BOTH, expand=TRUE)
c.create_window(0, 0, window=frame, anchor='nw')
#
lblSurvey=Label(frame, text="ENCUESTA", font=("Impact", 40))
lblSurvey.pack(side=TOP)
def guardar():
    cursor.execute("INSERT INTO resultado (a1,a2,a3,a4,a5,a6) VALUES ('%s','%s','%s','%s','%s','%s')" % (selec1.get(),selec2.get(),selec3.get(),selec4.get(),selec5.get(),selec6.get()))
    conexion.commit()
#
quest1=Label(frame, text="¿Qué tipo de música te gusta más?", font=("Impact"))
quest1.pack(side=TOP)
selec1=IntVar(frame)
rdBTipoR=Radiobutton(frame, text="Rock", value=1, variable=selec1)
rdBTipoR.pack(side=TOP)
rdBTipoP=Radiobutton(frame, text="Pop", value=2, variable=selec1)
rdBTipoP.pack(side=TOP)
rdBTipoI=Radiobutton(frame, text="Indie", value=3, variable=selec1)
rdBTipoI.pack(side=TOP)
rdBTipoRe=Radiobutton(frame, text="Reggae", value=4, variable=selec1)
rdBTipoRe.pack(side=TOP)
rdBTipoMe=Radiobutton(frame, text="Metal", value=5, variable=selec1)
rdBTipoMe.pack(side=TOP)
rdBTipoE=Radiobutton(frame, text="Electronic", value=6, variable=selec1)
rdBTipoE.pack(side=TOP)
rdBTipoRn=Radiobutton(frame, text="Reggaeton", value=7, variable=selec1)
rdBTipoRn.pack(side=TOP)
rdBTipoS=Radiobutton(frame, text="Salsa", value=8, variable=selec1)
rdBTipoS.pack(side=TOP)
rdBTipoJ=Radiobutton(frame, text="Jazz", value=9, variable=selec1)
rdBTipoJ.pack(side=TOP)
rdBTipoC=Radiobutton(frame, text="Clasic", value=10, variable=selec1)
rdBTipoC.pack(side=TOP)
rdBTipoO=Radiobutton(frame, text="Otro", value=11, variable=selec1)
rdBTipoO.pack(side=TOP)
#
separador1=Label(frame, text="")
separador1.pack(side=TOP)
#
quest2=Label(frame, text="¿Cuántas horas aproximadamente al día escuchas música?", font=("Impact"))
quest2.pack(side=TOP)
selec2=IntVar(frame)
rdBDe0=Radiobutton(frame, text="De 0 a 1 hora", value=1, variable=selec2)
rdBDe0.pack(side=TOP)
rdBDe1=Radiobutton(frame, text="De 1 a 3 horas", value=2, variable=selec2)
rdBDe1.pack(side=TOP)
rdBDe4=Radiobutton(frame, text="De 4 a 6 horas", value=3, variable=selec2)
rdBDe4.pack(side=TOP)
rdBDe7=Radiobutton(frame, text="De 7 a 10 horas", value=4, variable=selec2)
rdBDe7.pack(side=TOP)
rdBDe10=Radiobutton(frame, text="Mas de 10 horas", value=5, variable=selec2)
rdBDe10.pack(side=TOP)
#
separador2=Label(frame, text="")
separador2.pack(side=TOP)
#
quest3=Label(frame, text="¿Cuál fué la mejor década de la música?", font=("Impact"))
quest3.pack(side=TOP)
selec3=IntVar(frame)
rdBLos5=Radiobutton(frame, text="Los 50'", value=1, variable=selec3)
rdBLos5.pack(side=TOP)
rdBLos6=Radiobutton(frame, text="Los 60'", value=2, variable=selec3)
rdBLos6.pack(side=TOP)
rdBLos7=Radiobutton(frame, text="Los 70'", value=3, variable=selec3)
rdBLos7.pack(side=TOP)
rdBLos8=Radiobutton(frame, text="Los 80'", value=4, variable=selec3)
rdBLos8.pack(side=TOP)
rdBLos9=Radiobutton(frame, text="Los 90'", value=5, variable=selec3)
rdBLos9.pack(side=TOP)
rdBLos2=Radiobutton(frame, text="Década del 2000", value=6, variable=selec3)
rdBLos2.pack(side=TOP)
rdBEt=Radiobutton(frame, text="Estos tiempos", value=6, variable=selec3)
rdBEt.pack(side=TOP)
#
separador3=Label(frame, text="")
separador3.pack(side=TOP)
#
quest4=Label(frame, text="¿Para qué escuchas música?", font=("Impact"))
quest4.pack(side=TOP)
selec4=IntVar(frame)
rdBPdescan=Radiobutton(frame, text="Para descansar", value=1, variable=selec4)
rdBPdescan.pack(side=TOP)
rdBPdi=Radiobutton(frame, text="Para divertirme", value=2, variable=selec4)
rdBPdi.pack(side=TOP)
rdBPdese=Radiobutton(frame, text="Para desestresarme", value=3, variable=selec4)
rdBPdese.pack(side=TOP)
rdBPdescar=Radiobutton(frame, text="Para descargarme", value=4, variable=selec4)
rdBPdescar.pack(side=TOP)
rdBNa=Radiobutton(frame, text="Ninguna de las anteriores", value=6, variable=selec4)
rdBNa.pack(side=TOP)
#
separador4=Label(frame, text="")
separador4.pack(side=TOP)
#
quest5=Label(frame, text="En un concierto, ¿Qué sector prefieres?", font=("Impact"))
quest5.pack(side=TOP)
selec5=IntVar(frame)
rdBPf=Radiobutton(frame, text="Primera fila", value=1, variable=selec5)
rdBPf.pack(side=TOP)
rdBC=Radiobutton(frame, text="Campo", value=2, variable=selec5)
rdBC.pack(side=TOP)
rdBPl=Radiobutton(frame, text="Platea", value=3, variable=selec5)
rdBPl.pack(side=TOP)
rdBDb=Radiobutton(frame, text="Depende de la banda", value=4, variable=selec5)
rdBDb.pack(side=TOP)
rdBMm=Radiobutton(frame, text="Me da lo mismo", value=5, variable=selec5)
rdBMm.pack(side=TOP)
rdBNc=Radiobutton(frame, text="No voy a conciertos", value=6, variable=selec5)
rdBNc.pack(side=TOP)
#
separador5=Label(frame, text="")
separador5.pack(side=TOP)
#
quest6=Label(frame, text="¿Que tan importante es la música en tu vida?", font=("Impact"))
quest6.pack(side=TOP)
selec6=IntVar(frame)
rdBSm=Radiobutton(frame, text="Sin música no existo", value=1, variable=selec6)
rdBSm.pack(side=TOP)
rdBMi=Radiobutton(frame, text="Muy importante", value=2, variable=selec6)
rdBMi.pack(side=TOP)
rdBSe=Radiobutton(frame, text="Solo escucho música para pasar el rato", value=3, variable=selec6)
rdBSe.pack(side=TOP)
rdBNoe=Radiobutton(frame, text="No es importante", value=4, variable=selec6)
rdBNoe.pack(side=TOP)
#
separador6=Label(frame, text="")
separador6.pack(side=TOP)
#
root1.update()
c.config(scrollregion=c.bbox("all"))
#
botonGrabar=Button(root1,text='Enviar',command=guardar).place(x=0,y=25)
botonRegresarE=Button(c, text="← Return", font=("Calibri", 8), width=10, bg="#C9C9C9", activebackground="grey", activeforeground="white", cursor="hand2", command=retornar).place(x=0, y=0)
#imagenPi=PhotoImage(file="piano.png")
#lblImagenPi=Label(c, bd=0, image=imagenPi)

#Ventana results
root2=Tk()
root2.withdraw()
root2.title("Results")
root2.config(bg="black")
root2.geometry("800x418+100+100")
botonRegresarR=Button(root2, text="← Return", font=("Calibri", 8), width=10, bg="#C9C9C9", activebackground="grey", activeforeground="white", cursor="hand2", command=retornar).place(x=0, y=0)

#
root.mainloop()
root1.mainloop()
root2.mainloop()
